
package com.tigo.xmlns.portability.portabilityprocess.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.tigo.xmlns.portability.portabilityprocess.v1.schema.ExecuteTransactionRequest;
import com.tigo.xmlns.portability.portabilityprocess.v1.schema.ExecuteTransactionResponse;
import com.tigo.xmlns.portability.portabilityprocess.v1.schema.GetDevolutionRequest;
import com.tigo.xmlns.portability.portabilityprocess.v1.schema.GetDevolutionResponse;
import com.tigo.xmlns.portability.portabilityprocess.v1.schema.GetPendingInvoicesQuantityRequest;
import com.tigo.xmlns.portability.portabilityprocess.v1.schema.GetPendingInvoicesQuantityResponse;
import com.tigo.xmlns.portability.portabilityprocess.v1.schema.GetPortOutValidationRequest;
import com.tigo.xmlns.portability.portabilityprocess.v1.schema.GetPortOutValidationResponse;
import com.tigo.xmlns.portability.portabilityprocess.v1.schema.GetTransactionByMsisdnRequest;
import com.tigo.xmlns.portability.portabilityprocess.v1.schema.GetTransactionByMsisdnResponse;
import com.tigo.xmlns.portability.portabilityprocess.v1.schema.GetTransactionRequest;
import com.tigo.xmlns.portability.portabilityprocess.v1.schema.GetTransactionResponse;
import com.tigo.xmlns.portability.portabilityprocess.v1.schema.PortOutValidationRequest;
import com.tigo.xmlns.portability.portabilityprocess.v1.schema.PortOutValidationResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PortabilityProcessPortType", targetNamespace = "http://xmlns.tigo.com/Portability/PortabilityProcess/V1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.tigo.xmlns.portability.portabilityprocess.v1.schema.ObjectFactory.class,
    com.tigo.xmlns.parametertype.v2.ObjectFactory.class,
    com.tigo.xmlns.requestheader.v3.ObjectFactory.class,
    com.tigo.xmlns.responseheader.v3.ObjectFactory.class
})
public interface PortabilityProcessPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.tigo.xmlns.portability.portabilityprocess.v1.schema.PortOutValidationResponse
     */
    @WebMethod(action = "portOutValidation")
    @WebResult(name = "portOutValidationResponse", targetNamespace = "http://xmlns.tigo.com/Portability/PortabilityProcess/V1/schema", partName = "parameters")
    public PortOutValidationResponse portOutValidation(
        @WebParam(name = "portOutValidationRequest", targetNamespace = "http://xmlns.tigo.com/Portability/PortabilityProcess/V1/schema", partName = "parameters")
        PortOutValidationRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.tigo.xmlns.portability.portabilityprocess.v1.schema.GetPortOutValidationResponse
     */
    @WebMethod(action = "getPortOutValidation")
    @WebResult(name = "getPortOutValidationResponse", targetNamespace = "http://xmlns.tigo.com/Portability/PortabilityProcess/V1/schema", partName = "parameters")
    public GetPortOutValidationResponse getPortOutValidation(
        @WebParam(name = "getPortOutValidationRequest", targetNamespace = "http://xmlns.tigo.com/Portability/PortabilityProcess/V1/schema", partName = "parameters")
        GetPortOutValidationRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.tigo.xmlns.portability.portabilityprocess.v1.schema.ExecuteTransactionResponse
     */
    @WebMethod(action = "executeTransaction")
    @WebResult(name = "executeTransactionResponse", targetNamespace = "http://xmlns.tigo.com/Portability/PortabilityProcess/V1/schema", partName = "parameters")
    public ExecuteTransactionResponse executeTransaction(
        @WebParam(name = "executeTransactionRequest", targetNamespace = "http://xmlns.tigo.com/Portability/PortabilityProcess/V1/schema", partName = "parameters")
        ExecuteTransactionRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.tigo.xmlns.portability.portabilityprocess.v1.schema.GetTransactionResponse
     */
    @WebMethod(action = "getTransaction")
    @WebResult(name = "getTransactionResponse", targetNamespace = "http://xmlns.tigo.com/Portability/PortabilityProcess/V1/schema", partName = "parameters")
    public GetTransactionResponse getTransaction(
        @WebParam(name = "getTransactionRequest", targetNamespace = "http://xmlns.tigo.com/Portability/PortabilityProcess/V1/schema", partName = "parameters")
        GetTransactionRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.tigo.xmlns.portability.portabilityprocess.v1.schema.GetTransactionByMsisdnResponse
     */
    @WebMethod(action = "getTransactionByMsisdn")
    @WebResult(name = "getTransactionByMsisdnResponse", targetNamespace = "http://xmlns.tigo.com/Portability/PortabilityProcess/V1/schema", partName = "parameters")
    public GetTransactionByMsisdnResponse getTransactionByMsisdn(
        @WebParam(name = "getTransactionByMsisdnRequest", targetNamespace = "http://xmlns.tigo.com/Portability/PortabilityProcess/V1/schema", partName = "parameters")
        GetTransactionByMsisdnRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.tigo.xmlns.portability.portabilityprocess.v1.schema.GetDevolutionResponse
     */
    @WebMethod(action = "getDevolution")
    @WebResult(name = "getDevolutionResponse", targetNamespace = "http://xmlns.tigo.com/Portability/PortabilityProcess/V1/schema", partName = "parameters")
    public GetDevolutionResponse getDevolution(
        @WebParam(name = "getDevolutionRequest", targetNamespace = "http://xmlns.tigo.com/Portability/PortabilityProcess/V1/schema", partName = "parameters")
        GetDevolutionRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.tigo.xmlns.portability.portabilityprocess.v1.schema.GetPendingInvoicesQuantityResponse
     */
    @WebMethod(action = "getPendingInvoicesQuantity")
    @WebResult(name = "getPendingInvoicesQuantityResponse", targetNamespace = "http://xmlns.tigo.com/Portability/PortabilityProcess/V1/schema", partName = "parameters")
    public GetPendingInvoicesQuantityResponse getPendingInvoicesQuantity(
        @WebParam(name = "getPendingInvoicesQuantityRequest", targetNamespace = "http://xmlns.tigo.com/Portability/PortabilityProcess/V1/schema", partName = "parameters")
        GetPendingInvoicesQuantityRequest parameters);

}
