
package com.tigo.xmlns.portability.portabilityprocess.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PortabilityProcessService", targetNamespace = "http://xmlns.tigo.com/Portability/PortabilityProcess/V1", wsdlLocation = "file:/C:/lothar/sources/branches/paraguay/integracion/Netbeans/Varios/ServicioPortabilidadBO/src/conf/xml-resources/web-services/PortabilityProcessService/wsdl/10.252.100.63_8001/osb/Portability/PortabilityProcess/V1.wsdl")
public class PortabilityProcessService
    extends Service
{

    private final static URL PORTABILITYPROCESSSERVICE_WSDL_LOCATION;
    private final static WebServiceException PORTABILITYPROCESSSERVICE_EXCEPTION;
    private final static QName PORTABILITYPROCESSSERVICE_QNAME = new QName("http://xmlns.tigo.com/Portability/PortabilityProcess/V1", "PortabilityProcessService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/lothar/sources/branches/paraguay/integracion/Netbeans/Varios/ServicioPortabilidadBO/src/conf/xml-resources/web-services/PortabilityProcessService/wsdl/10.252.100.63_8001/osb/Portability/PortabilityProcess/V1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PORTABILITYPROCESSSERVICE_WSDL_LOCATION = url;
        PORTABILITYPROCESSSERVICE_EXCEPTION = e;
    }

    public PortabilityProcessService() {
        super(__getWsdlLocation(), PORTABILITYPROCESSSERVICE_QNAME);
    }

    public PortabilityProcessService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns PortabilityProcessPortType
     */
    @WebEndpoint(name = "PortabilityProcessPort")
    public PortabilityProcessPortType getPortabilityProcessPort() {
        return super.getPort(new QName("http://xmlns.tigo.com/Portability/PortabilityProcess/V1", "PortabilityProcessPort"), PortabilityProcessPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortabilityProcessPortType
     */
    @WebEndpoint(name = "PortabilityProcessPort")
    public PortabilityProcessPortType getPortabilityProcessPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.tigo.com/Portability/PortabilityProcess/V1", "PortabilityProcessPort"), PortabilityProcessPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PORTABILITYPROCESSSERVICE_EXCEPTION!= null) {
            throw PORTABILITYPROCESSSERVICE_EXCEPTION;
        }
        return PORTABILITYPROCESSSERVICE_WSDL_LOCATION;
    }

}
